services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ps14\KistNews\:
    resource: '../Classes/*'

  Ps14\KistNews\EventListener\NewsDetailListener:
    tags:
      - name: event.listener
        identifier: 'news-extended-detail'
        method: 'detailActionEvent'
        event: GeorgRinger\News\Event\NewsDetailActionEvent